
name: Upload ABIs

on:
  push:
    branches:
      - main
jobs:
    upload-artifact:
        runs-on: "ubuntu-latest"
        steps:
          - name: "Generate and prepare the contract artifacts"
            run: |
                mkdir abis
                for file in $(find src -name '*.sol'); do
                    contract_name=$(basename "$file" .sol)
                    forge inspect "$contract_name" abi > abi/"$contract_name".json
                done
          - name: "Store the contract artifacts in CI"
            uses: "actions/upload-artifact@v4"
            with:
                name: "contract-abis"
                path: "abis"